### ISSUE TITLE
Get rid of `purrr`

### ISSUE THREAD

**Issue by chainsawriot** [gesistsa/quanteda.dist#28]
Either with a simple for loop or rewrite in C/C++.

https://github.com/gesistsa/quanteda.proximity/blob/45b0dbd239a4bf2164a36f51550c716d3745ff3e/R/get_dist.R#L25

https://github.com/gesistsa/quanteda.proximity/blob/45b0dbd239a4bf2164a36f51550c716d3745ff3e/R/get_dist.R#L116-L125

**Comment by schochastics** [comment]
Lets try R. For 2nd one, this could work 
```r
    result_list <- mapply(
        FUN = .convert_df,
        tokens_obj = as.list(x),
        proximity_obj = quanteda::docvars(x, "proximity"),
        doc_id = quanteda::docnames(x),
        SIMPLIFY = FALSE
    )
    do.call(rbind, result_list)
```

**Comment by chainsawriot** [comment]
@schochastics Great! Please PR.

**Comment by chainsawriot** [comment]
May I assign this issue to you?

**Comment by schochastics** [comment]
@chainsawriot yes
