### ISSUE TITLE
`convert()` leaves row names

### ISSUE THREAD

**Issue by chainsawriot** [gesistsa/quanteda.dist#39]
248b329 and #28 

Another issue of `lapply` vs `purrr::map`, `lapply` and `do.call` leave row names.

**Comment by chainsawriot** [comment]
https://gesistsa.github.io/quanteda.proximity/articles/retrieval.html

**Comment by schochastics** [comment]
It seems to be only the mapply call that leaves names. Can be fixed with USE.NAMES = FALSE. Can make a PR if you want

**Comment by chainsawriot** [comment]
@schochastics Please. Thank you very much!
